= AdobeLightroomHacks

Just a bunch of things I found to hack adobe lighroom in my quest to synch better between applications I use, and not lose any info.

== Background

I've been using Adobe Lightroom for a long time, and it just got too expensive.  I was looking at other projects (listed below) but I didn't want to lose face data and location data.

This repository is the information I have disovered in my efforts to sync data between products and the raw `.xmp` sidecar files.

== Connecting

If you want to just snoop around the adobe data, you can use a product like https://dbeaver.io/[dbeaver] select the SQLite connector, and pick your `.lrcat` file to look around at the data.  

WARNING: be sure to use a backup copy of your lightroom catalogue file so that you don't lose any data.

== Other Software

### Free

* https://www.darktable.org/[DarkTable]
* https://rawtherapee.com/[rawtherapee]

### Paid

* https://www.captureone.com/[Capture One]

I will add more information as I go.
